### ISSUE TITLE
Make it possible to compile in ESP-IDF version 6.1

### ISSUE THREAD

**Issue by martinberlin** [vroland/epdiy#450]
Recently got a new Mac mini M4 and just to try it, downloaded latest **main** branch from ESP-IDF, this is result of trying to build Epdiy.
This happened in every major release so it does not surprise me at all. Maybe important also for @jonasschnelli and @mickeprag 

1. It seems **soc/lcd_periph.h** is not anymore there
epdiy/src/output_lcd/lcd_driver.c:14:10: fatal error: soc/lcd_periph.h: No such file or directory
   14 | #include <soc/lcd_periph.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

2. epdiy/src/board/epd_board_common.c:1:10: fatal error: **driver/adc.h**: No such file or directory
    1 | #include "driver/adc.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.

So far this 2 things seem to have moved somewhere else. Let's see what comes additionally once that is fixed.

**Comment by martinberlin** [comment]
What is the status here? Asking since I see that there is a revert commit.
